#pragma once

class Rules
{
public:
    static void Display()
    {
        std::cout << "\n\n\tPoints\n\n- Points are acquired one of three different ways.\n\t* A roll of a 1 is worth 100 points.\n\t* A roll of a 5 is worth 50 points.\n\t* Three(3) dice rolled at the same time with the same value is worth 100 times the face value, for\n\texample: three 2’s rolled is 200 points and three 5’s rolled is 500 points.\n\n- One exception to this rule is that three 1’s rolled is 1,000 points rather than 100 points\n\n";
        std::cout << "\tThe Play\n\n- The first player rolls all six dice at the same time and sets aside any “point dice” (1’s, 5’s, or\nthree of a kind) that appear.At this point, the player has the option to continue to roll the\nremaining dice to collect even more points, or stop and keep any points acquired.\n\n- A Farkle occurs when the dice are rolled and no point dice appear.At this point the player loses\nall the point dice he / she / it has collected during that turn,and the play passes to the player to\nthe left.No points are recorded for that player’s turn.\n\n- If a player decides not to risk rolling a Farkle then he / she / it can stop rolling and the play passes\nto the player to the left.Any points collected during that turn are then recorded.\n\n- If, in the course of one turn, all six dice become point diceand are set aside, the player must roll\nall six dice at least one more time, before stoppingand keeping the points collected.\n\n";
        std::cout << "\tWinning\n\n- In order to win, a player must get 10,000 points recorded.\n\n- After a player gets over 10,000, each of the other players get one turn to try to beat the first player who\ngoes out.If none of them beat his or her score, then he or she is declared the winner.If someone beats\nhis or her score then that new player wins the game.\n\n";
        std::cout << "\tEntering the Game\n\n- In order for a player to initially enter the game, (and record points), he / she must continue to roll\nuntil at least 1,000 points are collected during one turn. Once the player officially enters the\ngame, the points are recordedand that player may stop rolling at any time during future turns.\nSometimes it might take many turns before a player can get started.\n\n- Secret Strategy : All point dice do not have to be set aside.If you roll a 1 and a 5, sometimes it\nmay be strategic to keep the 1 and roll the 5 again with the rest of the non - point dice.This may\ngive you a better chance of rolling a three of a kind.But, at least one point die must be set aside\nafter each roll.\n\n";
    }
};